; mart types (see engine/items/mart.asm)
	const_def
	const MARTTYPE_STANDARD
	const MARTTYPE_HERBS
	const MARTTYPE_BARGAIN
	const MARTTYPE_PHARMACY
	const MARTTYPE_ROOFTOP
	const MARTTYPE_ROBBED
	const MARTTYPE_DRINKS
	const MARTTYPE_SUBWAY

; Marts indexes (see data/items/marts.asm)
	const_def
	const MART_ORCHID
	const MART_VIOLET
	const MART_PECTINIA
	const MART_CIANWOOD
	const MART_CIANWOOD_ROBBED
	const MART_DEPT_STORE_2F_1
	const MART_DEPT_STORE_2F_2
	const MART_DEPT_STORE_3F_1
	const MART_DEPT_STORE_3F_2
	const MART_DEPT_STORE_4F
	const MART_OLIVINE
	const MART_ECRUTEAK
	const MART_ECRUTEAK_TM
	const MART_MAHOGANY
	const MART_BLACKTHORN
	const MART_BLACKTHORN_TM
	const MART_FAVIA
	const MART_FAVIA_TM
	const MART_PEWTER
	const MART_CERULEAN
	const MART_LAVENDER
	const MART_VERMILION
	const MART_CELADON_2F_1
	const MART_CELADON_2F_2
	const MART_CELADON_3F
	const MART_CELADON_4F
	const MART_CELADON_5F_1
	const MART_CELADON_5F_2
	const MART_FUCHSIA
	const MART_SAFFRON
	const MART_MT_MOON
	const MART_INDIGO_PLATEAU
	const MART_INDIGO_PLATEAU_TM
	const MART_UNDERGROUND
