; StdScripts indexes (see engine/events/std_scripts.asm)
; also used in TileCollisionStdScripts (see data/events/collision_stdscripts.asm)
	enum_start
	enum pokecenternurse
	enum gymdoor
	enum entergym
	enum cantleavegym
	enum mailbox
	enum difficultbookshelf
	enum picturebookshelf
	enum magazinebookshelf
	enum teamrocketoath
	enum incenseburner
	enum merchandiseshelf
	enum capsulemachine
	enum gymgeyser
	enum strangesymbols
	enum oldstatue
	enum townmap
	enum window
	enum tv
	enum homepage
	enum radio1
	enum radio2
	enum trashcan
	enum strengthboulder
	enum smashrock
	enum pokecentersign
	enum martsign
	enum elevatorbutton
	enum daytotext
	enum firegymwarp
	enum safarizonewarp
	enum initializeevents
	enum gymstatue1
	enum gymstatue2
	enum gymstatue3
	enum gymstatue4
	enum receiveitem
	enum receivetogepiegg
	enum pcscript
	enum gamecornercoinvendor
	enum happinesschecknpc
	enum mysterygiftgirl
	enum lightuproom
	enum darkenroom
	enum darkenroomnoflash
	enum teleportguy
	enum stolenitemboxes
	enum wishingfountain
	enum emilycompanion
	enum battlesimexitwarp
	enum timetravelwarp
	enum battlesimencounter
	enum bosscelebiintro
	enum bosscelebidisappear
	enum celebiencounter_nobattle
	enum turntable
	enum incubator
	enum emptyincubator
