Route19_MapScripts:
	db 0 ; scene scripts

	db 0 ; callbacks
	
Route19TMSludgeBomb:
	itemball TM_SLUDGE_BOMB
	
Route19BigMushroom:
	hiddenitem BIG_MUSHROOM, EVENT_ROUTE_19_HIDDEN_BIG_MUSHROOM
	
Route19Stick:
	hiddenitem STICK, EVENT_ROUTE_19_HIDDEN_STICK

Route19_MapEvents:
	db 0, 0 ; filler

	db 0 ; warp events

	db 0 ; coord events

	db 2 ; bg events
	bg_event  8,  5, BGEVENT_ITEM, Route19BigMushroom
	bg_event 49, 16, BGEVENT_ITEM, Route19Stick

	db 9 ; object events
	object_event 46,  4, SPRITE_YOUNGSTER, SPRITEMOVEDATA_STANDING_LEFT, 0, 0, -1, -1, PAL_NPC_GREEN, OBJECTTYPE_TRAINER, 4, ObjectEvent, -1
	object_event 30, 12, SPRITE_YOUNGSTER, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, PAL_NPC_GREEN, OBJECTTYPE_TRAINER, 4, ObjectEvent, -1
	object_event 19,  9, SPRITE_YOUNGSTER, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, PAL_NPC_GREEN, OBJECTTYPE_TRAINER, 2, ObjectEvent, -1
	object_event  2,  9, SPRITE_YOUNGSTER, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, PAL_NPC_GREEN, OBJECTTYPE_TRAINER, 2, ObjectEvent, -1
	object_event  1, 10, SPRITE_YOUNGSTER, SPRITEMOVEDATA_STANDING_RIGHT, 0, 0, -1, -1, PAL_NPC_GREEN, OBJECTTYPE_TRAINER, 2, ObjectEvent, -1
	object_event  0, 16, SPRITE_YOUNGSTER, SPRITEMOVEDATA_STANDING_RIGHT, 0, 0, -1, -1, PAL_NPC_GREEN, OBJECTTYPE_TRAINER, 3, ObjectEvent, -1
	object_event 32,  6, SPRITE_POKE_BALL, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, 0, OBJECTTYPE_ITEMBALL, 0, ObjectEvent, -1
	object_event 24, 21, SPRITE_POKE_BALL, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, 0, OBJECTTYPE_ITEMBALL, 0, ObjectEvent, -1
	object_event  1,  9, SPRITE_POKE_BALL, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, PAL_NPC_SILVER, OBJECTTYPE_ITEMBALL, 0, Route19TMSludgeBomb, EVENT_GOT_TM_SLUDGE_BOMB
