; Footprints are 2x2 tiles each, but are stored as a 16x64-tile image
; (32 rows of 8 footprints per row).
; That means there's a row of the top two tiles for eight footprints,
; then a row of the bottom two tiles for those eight footprints.

; These macros help extract the first and the last two tiles, respectively.
footprint_top    EQUS "0,                 2 * LEN_1BPP_TILE"
footprint_bottom EQUS "2 * LEN_1BPP_TILE, 2 * LEN_1BPP_TILE"

; Entries correspond to Pokémon species, two apiece, 8 tops then 8 bottoms

; 001-008 first type
INCBIN "gfx/footprints/types/grass.1bpp",  footprint_top ;Bulbasaur
INCBIN "gfx/footprints/types/grass.1bpp",    footprint_top ;Ivysaur
INCBIN "gfx/footprints/types/grass.1bpp",   footprint_top ;Venusaur
INCBIN "gfx/footprints/types/fire.1bpp", footprint_top ;Charmander
INCBIN "gfx/footprints/types/fire.1bpp", footprint_top ;Charmeleon
INCBIN "gfx/footprints/types/fire.1bpp",  footprint_top ;Charizard
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Squirtle
INCBIN "gfx/footprints/types/water.1bpp",  footprint_top ;Wartortle
; 001-008 second type
INCBIN "gfx/footprints/types/poison.1bpp",  footprint_bottom ;Bulbasaur
INCBIN "gfx/footprints/types/poison.1bpp",    footprint_bottom ;Ivysaur
INCBIN "gfx/footprints/types/poison.1bpp",   footprint_bottom ;Venusaur
INCBIN "gfx/footprints/types/none.1bpp", footprint_bottom ;Charmander
INCBIN "gfx/footprints/types/none.1bpp", footprint_bottom ;Charmeleon
INCBIN "gfx/footprints/types/flying.1bpp",  footprint_bottom ;Charizard
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Squirtle
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Wartortle
; 009-016 first type
INCBIN "gfx/footprints/types/water.1bpp",  footprint_top ;Blastoise
INCBIN "gfx/footprints/types/bug.1bpp",   footprint_top ;Caterpie
INCBIN "gfx/footprints/types/bug.1bpp",    footprint_top ;Metapod
INCBIN "gfx/footprints/types/bug.1bpp", footprint_top ;Butterfree
INCBIN "gfx/footprints/types/bug.1bpp",     footprint_top ;Weedle
INCBIN "gfx/footprints/types/bug.1bpp",     footprint_top ;Kakuna
INCBIN "gfx/footprints/types/bug.1bpp",   footprint_top ;Beedrill
INCBIN "gfx/footprints/types/normal.1bpp",     footprint_top ;Pidgey
; 009-016 second type
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Blastoise
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Caterpie
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Metapod
INCBIN "gfx/footprints/types/flying.1bpp", footprint_bottom ;Butterfree
INCBIN "gfx/footprints/types/poison.1bpp",     footprint_bottom ;Weedle
INCBIN "gfx/footprints/types/poison.1bpp",     footprint_bottom ;Kakuna
INCBIN "gfx/footprints/types/poison.1bpp",   footprint_bottom ;Beedrill
INCBIN "gfx/footprints/types/flying.1bpp",     footprint_bottom ;Pidgey
; 017-024 first type
INCBIN "gfx/footprints/types/normal.1bpp",  footprint_top ;Pidgeotto
INCBIN "gfx/footprints/types/normal.1bpp",    footprint_top ;Pidgeot
INCBIN "gfx/footprints/types/dark.1bpp",    footprint_top ;Rinring
INCBIN "gfx/footprints/types/dark.1bpp",   footprint_top ;Nyanell
INCBIN "gfx/footprints/types/normal.1bpp",    footprint_top ;Spearow
INCBIN "gfx/footprints/types/normal.1bpp",     footprint_top ;Fearow
INCBIN "gfx/footprints/types/poison.1bpp",      footprint_top ;Ekans
INCBIN "gfx/footprints/types/poison.1bpp",      footprint_top ;Arbok
; 017-024 second type
INCBIN "gfx/footprints/types/flying.1bpp",  footprint_bottom ;Pidgeotto
INCBIN "gfx/footprints/types/flying.1bpp",    footprint_bottom ;Pidgeot
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Rinring
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Nyanell
INCBIN "gfx/footprints/types/flying.1bpp",    footprint_bottom ;Spearow
INCBIN "gfx/footprints/types/flying.1bpp",     footprint_bottom ;Fearow
INCBIN "gfx/footprints/types/none.1bpp",      footprint_bottom ;Ekans
INCBIN "gfx/footprints/types/none.1bpp",      footprint_bottom ;Arbok
; 025-032 first type
INCBIN "gfx/footprints/types/electric.1bpp",    footprint_top ;Pikachu
INCBIN "gfx/footprints/types/electric.1bpp",     footprint_top ;Raichu
INCBIN "gfx/footprints/types/ground.1bpp",  footprint_top ;Sandshrew
INCBIN "gfx/footprints/types/ground.1bpp",  footprint_top ;Sandslash
INCBIN "gfx/footprints/types/poison.1bpp",  footprint_top ;NidoranF
INCBIN "gfx/footprints/types/poison.1bpp",   footprint_top ;Nidorina
INCBIN "gfx/footprints/types/poison.1bpp",  footprint_top ;Nidoqueen
INCBIN "gfx/footprints/types/poison.1bpp",  footprint_top ;NidoranM
; 025-032 second type
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Pikachu
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Raichu
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Sandshrew
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Sandslash
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;NidoranF
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Nidorina
INCBIN "gfx/footprints/types/ground.1bpp",  footprint_bottom ;Nidoqueen
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;NidoranM
; 033-040 first type
INCBIN "gfx/footprints/types/poison.1bpp",   footprint_top ;Nidorino
INCBIN "gfx/footprints/types/poison.1bpp",   footprint_top ;Nidoking
INCBIN "gfx/footprints/types/fairy.1bpp",   footprint_top ;Clefairy
INCBIN "gfx/footprints/types/fairy.1bpp",   footprint_top ;Clefable
INCBIN "gfx/footprints/types/fire.1bpp",     footprint_top ;Vulpix
INCBIN "gfx/footprints/types/fire.1bpp",  footprint_top ;Ninetales
INCBIN "gfx/footprints/types/normal.1bpp", footprint_top ;Jigglypuff
INCBIN "gfx/footprints/types/normal.1bpp", footprint_top ;Wigglytuff
; 033-040 second type
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Nidorino
INCBIN "gfx/footprints/types/ground.1bpp",   footprint_bottom ;Nidoking
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Clefairy
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Clefable
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Vulpix
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Ninetales
INCBIN "gfx/footprints/types/fairy.1bpp", footprint_bottom ;Jigglypuff
INCBIN "gfx/footprints/types/fairy.1bpp", footprint_bottom ;Wigglytuff
; 041-048 first type
INCBIN "gfx/footprints/types/poison.1bpp",      footprint_top ;Zubat
INCBIN "gfx/footprints/types/poison.1bpp",     footprint_top ;Golbat
INCBIN "gfx/footprints/types/grass.1bpp",     footprint_top ;Oddish
INCBIN "gfx/footprints/types/grass.1bpp",      footprint_top ;Gloom
INCBIN "gfx/footprints/types/grass.1bpp",  footprint_top ;Vileplume
INCBIN "gfx/footprints/types/bug.1bpp",      footprint_top ;Paras
INCBIN "gfx/footprints/types/bug.1bpp",   footprint_top ;Parasect
INCBIN "gfx/footprints/types/bug.1bpp",    footprint_top ;Venonat
; 041-048 second type
INCBIN "gfx/footprints/types/flying.1bpp",      footprint_bottom ;Zubat
INCBIN "gfx/footprints/types/flying.1bpp",     footprint_bottom ;Golbat
INCBIN "gfx/footprints/types/poison.1bpp",     footprint_bottom ;Oddish
INCBIN "gfx/footprints/types/poison.1bpp",      footprint_bottom ;Gloom
INCBIN "gfx/footprints/types/poison.1bpp",  footprint_bottom ;Vileplume
INCBIN "gfx/footprints/types/grass.1bpp",      footprint_bottom ;Paras
INCBIN "gfx/footprints/types/grass.1bpp",   footprint_bottom ;Parasect
INCBIN "gfx/footprints/types/poison.1bpp",    footprint_bottom ;Venonat
; 049-056 first type
INCBIN "gfx/footprints/types/bug.1bpp",   footprint_top ;Venomoth
INCBIN "gfx/footprints/types/ground.1bpp",    footprint_top ;Diglett
INCBIN "gfx/footprints/types/ground.1bpp",    footprint_top ;Dugtrio
INCBIN "gfx/footprints/types/normal.1bpp",     footprint_top ;Meowth
INCBIN "gfx/footprints/types/normal.1bpp",    footprint_top ;Persian
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;S'Mola
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Ancor
INCBIN "gfx/footprints/types/fighting.1bpp",     footprint_top ;Mankey
; 049-056 second type
INCBIN "gfx/footprints/types/poison.1bpp",   footprint_bottom ;Venomoth
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Diglett
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Dugtrio
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Meowth
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Persian
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;S'Mola
INCBIN "gfx/footprints/types/steel.1bpp",    footprint_bottom ;Ancor
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Mankey
; 057-064 first type
INCBIN "gfx/footprints/types/fighting.1bpp",   footprint_top ;Primeape
INCBIN "gfx/footprints/types/fire.1bpp",  footprint_top ;Growlithe
INCBIN "gfx/footprints/types/fire.1bpp",   footprint_top ;Arcanine
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Poliwag
INCBIN "gfx/footprints/types/water.1bpp",  footprint_top ;Poliwhirl
INCBIN "gfx/footprints/types/water.1bpp",  footprint_top ;Poliwrath
INCBIN "gfx/footprints/types/psychic.1bpp",       footprint_top ;Abra
INCBIN "gfx/footprints/types/psychic.1bpp",    footprint_top ;Kadabra
; 057-064 second type
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Primeape
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Growlithe
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Arcanine
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Poliwag
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Poliwhirl
INCBIN "gfx/footprints/types/fighting.1bpp",  footprint_bottom ;Poliwrath
INCBIN "gfx/footprints/types/none.1bpp",       footprint_bottom ;Abra
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Kadabra
; 065-072 first type
INCBIN "gfx/footprints/types/psychic.1bpp",   footprint_top ;Alakazam
INCBIN "gfx/footprints/types/fighting.1bpp",     footprint_top ;Machop
INCBIN "gfx/footprints/types/fighting.1bpp",    footprint_top ;Machoke
INCBIN "gfx/footprints/types/fighting.1bpp",    footprint_top ;Machamp
INCBIN "gfx/footprints/types/grass.1bpp", footprint_top ;Bellsprout
INCBIN "gfx/footprints/types/grass.1bpp", footprint_top ;Weepinbell
INCBIN "gfx/footprints/types/grass.1bpp", footprint_top ;Victreebel
INCBIN "gfx/footprints/types/water.1bpp",  footprint_top ;Tentacool
; 065-072 second type
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Alakazam
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Machop
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Machoke
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Machamp
INCBIN "gfx/footprints/types/poison.1bpp", footprint_bottom ;Bellsprout
INCBIN "gfx/footprints/types/poison.1bpp", footprint_bottom ;Weepinbell
INCBIN "gfx/footprints/types/poison.1bpp", footprint_bottom ;Victreebel
INCBIN "gfx/footprints/types/poison.1bpp",  footprint_bottom ;Tentacool
; 073-080 first type
INCBIN "gfx/footprints/types/water.1bpp", footprint_top ;Tentacruel
INCBIN "gfx/footprints/types/rock.1bpp",    footprint_top ;Geodude
INCBIN "gfx/footprints/types/rock.1bpp",   footprint_top ;Graveler
INCBIN "gfx/footprints/types/rock.1bpp",      footprint_top ;Golem
INCBIN "gfx/footprints/types/fire.1bpp",     footprint_top ;Ponyta
INCBIN "gfx/footprints/types/fire.1bpp",   footprint_top ;Rapidash
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Slowpoke
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Slowbro
; 073-080 second type
INCBIN "gfx/footprints/types/poison.1bpp", footprint_bottom ;Tentacruel
INCBIN "gfx/footprints/types/ground.1bpp",    footprint_bottom ;Geodude
INCBIN "gfx/footprints/types/ground.1bpp",   footprint_bottom ;Graveler
INCBIN "gfx/footprints/types/ground.1bpp",      footprint_bottom ;Golem
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Ponyta
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Rapidash
INCBIN "gfx/footprints/types/psychic.1bpp",   footprint_bottom ;Slowpoke
INCBIN "gfx/footprints/types/psychic.1bpp",    footprint_bottom ;Slowbro
; 081-088 first type
INCBIN "gfx/footprints/types/electric.1bpp",  footprint_top ;Magnemite
INCBIN "gfx/footprints/types/electric.1bpp",   footprint_top ;Magneton
INCBIN "gfx/footprints/types/normal.1bpp", footprint_top ;Farfetch'd
INCBIN "gfx/footprints/types/normal.1bpp",      footprint_top ;Doduo
INCBIN "gfx/footprints/types/normal.1bpp",     footprint_top ;Dodrio
INCBIN "gfx/footprints/types/water.1bpp",       footprint_top ;Seel
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Dewgong
INCBIN "gfx/footprints/types/poison.1bpp",     footprint_top ;Grimer
; 081-088 second type
INCBIN "gfx/footprints/types/steel.1bpp",  footprint_bottom ;Magnemite
INCBIN "gfx/footprints/types/steel.1bpp",   footprint_bottom ;Magneton
INCBIN "gfx/footprints/types/flying.1bpp", footprint_bottom ;Farfetch'd
INCBIN "gfx/footprints/types/flying.1bpp",      footprint_bottom ;Doduo
INCBIN "gfx/footprints/types/flying.1bpp",     footprint_bottom ;Dodrio
INCBIN "gfx/footprints/types/none.1bpp",       footprint_bottom ;Seel
INCBIN "gfx/footprints/types/ice.1bpp",    footprint_bottom ;Dewgong
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Grimer
; 089-096 first type
INCBIN "gfx/footprints/types/poison.1bpp",        footprint_top ;Muk
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Shellder
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Cloyster
INCBIN "gfx/footprints/types/ghost.1bpp",     footprint_top ;Gastly
INCBIN "gfx/footprints/types/ghost.1bpp",    footprint_top ;Haunter
INCBIN "gfx/footprints/types/ghost.1bpp",     footprint_top ;Gengar
INCBIN "gfx/footprints/types/rock.1bpp",       footprint_top ;Onix
INCBIN "gfx/footprints/types/psychic.1bpp",    footprint_top ;Drowzee
; 089-096 second type
INCBIN "gfx/footprints/types/dark.1bpp",        footprint_bottom ;Muk
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Shellder
INCBIN "gfx/footprints/types/ice.1bpp",   footprint_bottom ;Cloyster
INCBIN "gfx/footprints/types/poison.1bpp",     footprint_bottom ;Gastly
INCBIN "gfx/footprints/types/poison.1bpp",    footprint_bottom ;Haunter
INCBIN "gfx/footprints/types/poison.1bpp",     footprint_bottom ;Gengar
INCBIN "gfx/footprints/types/ground.1bpp",       footprint_bottom ;Onix
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Drowzee
; 097-104 first type
INCBIN "gfx/footprints/types/psychic.1bpp",      footprint_top ;Hypno
INCBIN "gfx/footprints/types/water.1bpp",     footprint_top ;Krabby
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Kingler
INCBIN "gfx/footprints/types/electric.1bpp",    footprint_top ;Voltorb
INCBIN "gfx/footprints/types/electric.1bpp",  footprint_top ;Electrode
INCBIN "gfx/footprints/types/grass.1bpp",  footprint_top ;Exeggcute
INCBIN "gfx/footprints/types/psychic.1bpp",  footprint_top ;Exeggutor
INCBIN "gfx/footprints/types/ground.1bpp",     footprint_top ;Cubone
; 097-104 second type
INCBIN "gfx/footprints/types/none.1bpp",      footprint_bottom ;Hypno
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Krabby
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Kingler
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Voltorb
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Electrode
INCBIN "gfx/footprints/types/psychic.1bpp",  footprint_bottom ;Exeggcute
INCBIN "gfx/footprints/types/psychic.1bpp",  footprint_bottom ;Exeggutor
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Cubone
; 105-112 first type
INCBIN "gfx/footprints/types/ground.1bpp",    footprint_top ;Marowak
INCBIN "gfx/footprints/types/water.1bpp",  footprint_top ;Concher
INCBIN "gfx/footprints/types/water.1bpp", footprint_top ;Searion
INCBIN "gfx/footprints/types/normal.1bpp",  footprint_top ;Lickitung
INCBIN "gfx/footprints/types/poison.1bpp",    footprint_top ;Koffing
INCBIN "gfx/footprints/types/poison.1bpp",    footprint_top ;Weezing
INCBIN "gfx/footprints/types/rock.1bpp",    footprint_top ;Rhyhorn
INCBIN "gfx/footprints/types/rock.1bpp",     footprint_top ;Rhydon
; 105-112 second type
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Marowak
INCBIN "gfx/footprints/types/ice.1bpp",  footprint_bottom ;Concher
INCBIN "gfx/footprints/types/fire.1bpp", footprint_bottom ;Searion
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Lickitung
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Koffing
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Weezing
INCBIN "gfx/footprints/types/ground.1bpp",    footprint_bottom ;Rhyhorn
INCBIN "gfx/footprints/types/ground.1bpp",     footprint_bottom ;Rhydon
; 113-120 first type
INCBIN "gfx/footprints/types/normal.1bpp",    footprint_top ;Chansey
INCBIN "gfx/footprints/types/grass.1bpp",    footprint_top ;Tangela
INCBIN "gfx/footprints/types/normal.1bpp", footprint_top ;Kangaskhan
INCBIN "gfx/footprints/types/water.1bpp",     footprint_top ;Horsea
INCBIN "gfx/footprints/types/water.1bpp",     footprint_top ;Seadra 
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Goldeen
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Seaking
INCBIN "gfx/footprints/types/water.1bpp",     footprint_top ;Staryu
; 113-120 second type
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Chansey
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Tangela
INCBIN "gfx/footprints/types/none.1bpp", footprint_bottom ;Kangaskhan
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Horsea
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Seadra 
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Goldeen
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Seaking
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Staryu
; 121-128 first type
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Starmie
INCBIN "gfx/footprints/types/psychic.1bpp",   footprint_top ;Mr. Mime
INCBIN "gfx/footprints/types/bug.1bpp",    footprint_top ;Scyther
INCBIN "gfx/footprints/types/ice.1bpp",       footprint_top ;Jynx
INCBIN "gfx/footprints/types/electric.1bpp", footprint_top ;Electabuzz
INCBIN "gfx/footprints/types/fire.1bpp",     footprint_top ;Magmar
INCBIN "gfx/footprints/types/bug.1bpp",     footprint_top ;Pinsir
INCBIN "gfx/footprints/types/normal.1bpp",     footprint_top ;Tauros
; 121-128 second type
INCBIN "gfx/footprints/types/psychic.1bpp",    footprint_bottom ;Starmie
INCBIN "gfx/footprints/types/fairy.1bpp",   footprint_bottom ;Mr. Mime
INCBIN "gfx/footprints/types/flying.1bpp",    footprint_bottom ;Scyther
INCBIN "gfx/footprints/types/psychic.1bpp",       footprint_bottom ;Jynx
INCBIN "gfx/footprints/types/none.1bpp", footprint_bottom ;Electabuzz
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Magmar
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Pinsir
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Tauros
; 129-136 first type
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Magikarp
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Gyarados
INCBIN "gfx/footprints/types/water.1bpp",     footprint_top ;Lapras
INCBIN "gfx/footprints/types/normal.1bpp",      footprint_top ;Ditto
INCBIN "gfx/footprints/types/normal.1bpp",      footprint_top ;Eevee
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Vaporeon
INCBIN "gfx/footprints/types/electric.1bpp",    footprint_top ;Jolteon
INCBIN "gfx/footprints/types/fire.1bpp",    footprint_top ;Flareon
; 129-136 second type
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Magikarp
INCBIN "gfx/footprints/types/flying.1bpp",   footprint_bottom ;Gyarados
INCBIN "gfx/footprints/types/ice.1bpp",     footprint_bottom ;Lapras
INCBIN "gfx/footprints/types/none.1bpp",      footprint_bottom ;Ditto
INCBIN "gfx/footprints/types/none.1bpp",      footprint_bottom ;Eevee
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Vaporeon
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Jolteon
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Flareon
; 137-144 first type
INCBIN "gfx/footprints/types/normal.1bpp",    footprint_top ;Porygon
INCBIN "gfx/footprints/types/rock.1bpp",    footprint_top ;Omanyte
INCBIN "gfx/footprints/types/rock.1bpp",    footprint_top ;Omastar
INCBIN "gfx/footprints/types/rock.1bpp",     footprint_top ;Kabuto
INCBIN "gfx/footprints/types/rock.1bpp",   footprint_top ;Kabutops
INCBIN "gfx/footprints/types/rock.1bpp", footprint_top ;Aerodactyl
INCBIN "gfx/footprints/types/normal.1bpp",    footprint_top ;Snorlax
INCBIN "gfx/footprints/types/ice.1bpp",   footprint_top ;Articuno
; 137-144 second type
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Porygon
INCBIN "gfx/footprints/types/water.1bpp",    footprint_bottom ;Omanyte
INCBIN "gfx/footprints/types/water.1bpp",    footprint_bottom ;Omastar
INCBIN "gfx/footprints/types/water.1bpp",     footprint_bottom ;Kabuto
INCBIN "gfx/footprints/types/water.1bpp",   footprint_bottom ;Kabutops
INCBIN "gfx/footprints/types/flying.1bpp", footprint_bottom ;Aerodactyl
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Snorlax
INCBIN "gfx/footprints/types/flying.1bpp",   footprint_bottom ;Articuno
; 145-152 first type
INCBIN "gfx/footprints/types/electric.1bpp",     footprint_top ;Zapdos
INCBIN "gfx/footprints/types/fire.1bpp",    footprint_top ;Moltres
INCBIN "gfx/footprints/types/dragon.1bpp",    footprint_top ;Dratini
INCBIN "gfx/footprints/types/dragon.1bpp",  footprint_top ;Dragonair
INCBIN "gfx/footprints/types/dragon.1bpp",  footprint_top ;Dragonite
INCBIN "gfx/footprints/types/psychic.1bpp",     footprint_top ;Mewtwo
INCBIN "gfx/footprints/types/psychic.1bpp",        footprint_top ;Mew
INCBIN "gfx/footprints/types/grass.1bpp",  footprint_top ;Chikorita
; 145-152 second type
INCBIN "gfx/footprints/types/flying.1bpp",     footprint_bottom ;Zapdos
INCBIN "gfx/footprints/types/flying.1bpp",    footprint_bottom ;Moltres
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Dratini
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Dragonair
INCBIN "gfx/footprints/types/flying.1bpp",  footprint_bottom ;Dragonite
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Mewtwo
INCBIN "gfx/footprints/types/none.1bpp",        footprint_bottom ;Mew
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Chikorita
; 153-160 first type
INCBIN "gfx/footprints/types/grass.1bpp",    footprint_top ;Bayleef
INCBIN "gfx/footprints/types/grass.1bpp",   footprint_top ;Meganium
INCBIN "gfx/footprints/types/fire.1bpp",  footprint_top ;Cyndaquil
INCBIN "gfx/footprints/types/fire.1bpp",    footprint_top ;Quilava
INCBIN "gfx/footprints/types/fire.1bpp", footprint_top ;Typhlosion
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Totodile
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Croconaw
INCBIN "gfx/footprints/types/water.1bpp", footprint_top ;Feraligatr
; 153-160 second type
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Bayleef
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Meganium
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Cyndaquil
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Quilava
INCBIN "gfx/footprints/types/none.1bpp", footprint_bottom ;Typhlosion
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Totodile
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Croconaw
INCBIN "gfx/footprints/types/none.1bpp", footprint_bottom ;Feraligatr
; 161-168 first type
INCBIN "gfx/footprints/types/normal.1bpp",    footprint_top ;Sentret
INCBIN "gfx/footprints/types/normal.1bpp",     footprint_top ;Furret
INCBIN "gfx/footprints/types/normal.1bpp",   footprint_top ;Hoothoot
INCBIN "gfx/footprints/types/normal.1bpp",    footprint_top ;Noctowl
INCBIN "gfx/footprints/types/electric.1bpp",    footprint_top ;Cubbolt
INCBIN "gfx/footprints/types/electric.1bpp",  footprint_top ;Electiger
INCBIN "gfx/footprints/types/bug.1bpp",   footprint_top ;Spinarak
INCBIN "gfx/footprints/types/bug.1bpp",    footprint_top ;Ariados
; 161-168 second type
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Sentret
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Furret
INCBIN "gfx/footprints/types/flying.1bpp",   footprint_bottom ;Hoothoot
INCBIN "gfx/footprints/types/flying.1bpp",    footprint_bottom ;Noctowl
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Cubbolt
INCBIN "gfx/footprints/types/dark.1bpp",  footprint_bottom ;Electiger
INCBIN "gfx/footprints/types/poison.1bpp",   footprint_bottom ;Spinarak
INCBIN "gfx/footprints/types/poison.1bpp",    footprint_bottom ;Ariados
; 169-176 first type
INCBIN "gfx/footprints/types/poison.1bpp",     footprint_top ;Crobat
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Chinchou
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Lanturn
INCBIN "gfx/footprints/types/electric.1bpp",      footprint_top ;Pichu
INCBIN "gfx/footprints/types/fairy.1bpp",     footprint_top ;Cleffa
INCBIN "gfx/footprints/types/normal.1bpp",  footprint_top ;Igglybuff
INCBIN "gfx/footprints/types/ice.1bpp",     footprint_top ;Shifur
INCBIN "gfx/footprints/types/ice.1bpp",    footprint_top ;Snowmad
; 169-176 second type
INCBIN "gfx/footprints/types/flying.1bpp",     footprint_bottom ;Crobat
INCBIN "gfx/footprints/types/electric.1bpp",   footprint_bottom ;Chinchou
INCBIN "gfx/footprints/types/electric.1bpp",    footprint_bottom ;Lanturn
INCBIN "gfx/footprints/types/none.1bpp",      footprint_bottom ;Pichu
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Cleffa
INCBIN "gfx/footprints/types/fairy.1bpp",  footprint_bottom ;Igglybuff
INCBIN "gfx/footprints/types/normal.1bpp",     footprint_bottom ;Shifur
INCBIN "gfx/footprints/types/dark.1bpp",    footprint_bottom ;Snowmad
; 177-184 first type
INCBIN "gfx/footprints/types/psychic.1bpp",       footprint_top ;Natu
INCBIN "gfx/footprints/types/psychic.1bpp",       footprint_top ;Xatu
INCBIN "gfx/footprints/types/electric.1bpp",     footprint_top ;Mareep
INCBIN "gfx/footprints/types/electric.1bpp",    footprint_top ;Flaaffy
INCBIN "gfx/footprints/types/electric.1bpp",   footprint_top ;Ampharos
INCBIN "gfx/footprints/types/grass.1bpp",  footprint_top ;Bellossom
INCBIN "gfx/footprints/types/water.1bpp",     footprint_top ;Marill
INCBIN "gfx/footprints/types/water.1bpp",  footprint_top ;Azumarill
; 177-184 second type
INCBIN "gfx/footprints/types/flying.1bpp",       footprint_bottom ;Natu
INCBIN "gfx/footprints/types/flying.1bpp",       footprint_bottom ;Xatu
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Mareep
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Flaaffy
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Ampharos
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Bellossom
INCBIN "gfx/footprints/types/fairy.1bpp",     footprint_bottom ;Marill
INCBIN "gfx/footprints/types/fairy.1bpp",  footprint_bottom ;Azumarill
; 185-192 first type
INCBIN "gfx/footprints/types/rock.1bpp",  footprint_top ;Sudowoodo
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Politoed
INCBIN "gfx/footprints/types/grass.1bpp",     footprint_top ;Hoppio
INCBIN "gfx/footprints/types/grass.1bpp",   footprint_top ;Skiploom
INCBIN "gfx/footprints/types/grass.1bpp",   footprint_top ;Jumpluff
INCBIN "gfx/footprints/types/normal.1bpp",      footprint_top ;Aipom
INCBIN "gfx/footprints/types/grass.1bpp",    footprint_top ;Sunkern
INCBIN "gfx/footprints/types/grass.1bpp",   footprint_top ;Sunflora
; 185-192 second type
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Sudowoodo
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Politoed
INCBIN "gfx/footprints/types/flying.1bpp",     footprint_bottom ;Hoppio
INCBIN "gfx/footprints/types/flying.1bpp",   footprint_bottom ;Skiploom
INCBIN "gfx/footprints/types/flying.1bpp",   footprint_bottom ;Jumpluff
INCBIN "gfx/footprints/types/none.1bpp",      footprint_bottom ;Aipom
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Sunkern
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Sunflora
; 193-200 first type
INCBIN "gfx/footprints/types/bug.1bpp",      footprint_top ;Yanma
INCBIN "gfx/footprints/types/water.1bpp",     footprint_top ;Wooper
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Quagsire
INCBIN "gfx/footprints/types/psychic.1bpp",     footprint_top ;Espeon
INCBIN "gfx/footprints/types/dark.1bpp",    footprint_top ;Umbreon
INCBIN "gfx/footprints/types/dark.1bpp",    footprint_top ;Murkow
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Slowking
INCBIN "gfx/footprints/types/ghost.1bpp", footprint_top ;Misdreavus
; 193-200 second type
INCBIN "gfx/footprints/types/flying.1bpp",      footprint_bottom ;Yanma
INCBIN "gfx/footprints/types/ground.1bpp",     footprint_bottom ;Wooper
INCBIN "gfx/footprints/types/ground.1bpp",   footprint_bottom ;Quagsire
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Espeon
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Umbreon
INCBIN "gfx/footprints/types/flying.1bpp",    footprint_bottom ;Murkow
INCBIN "gfx/footprints/types/psychic.1bpp",   footprint_bottom ;Slowking
INCBIN "gfx/footprints/types/none.1bpp", footprint_bottom ;Misdreavus
; 201-208 first type
INCBIN "gfx/footprints/types/psychic.1bpp",      footprint_top ;Unown
INCBIN "gfx/footprints/types/psychic.1bpp",  footprint_top ;Wobbuffet
INCBIN "gfx/footprints/types/normal.1bpp",  footprint_top ;Girafarig
INCBIN "gfx/footprints/types/bug.1bpp",     footprint_top ;Pineco
INCBIN "gfx/footprints/types/bug.1bpp", footprint_top ;Forretress
INCBIN "gfx/footprints/types/normal.1bpp",  footprint_top ;Dunsparce
INCBIN "gfx/footprints/types/ground.1bpp",     footprint_top ;Gligar
INCBIN "gfx/footprints/types/steel.1bpp",    footprint_top ;Steelix
; 201-208 second type
INCBIN "gfx/footprints/types/none.1bpp",      footprint_bottom ;Unown
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Wobbuffet
INCBIN "gfx/footprints/types/psychic.1bpp",  footprint_bottom ;Girafarig
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Pineco
INCBIN "gfx/footprints/types/steel.1bpp", footprint_bottom ;Forretress
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Dunsparce
INCBIN "gfx/footprints/types/flying.1bpp",     footprint_bottom ;Gligar
INCBIN "gfx/footprints/types/ground.1bpp",    footprint_bottom ;Steelix
; 209-216 first type
INCBIN "gfx/footprints/types/fairy.1bpp",   footprint_top ;Snubbull
INCBIN "gfx/footprints/types/fairy.1bpp",   footprint_top ;Granbull
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Qwilfish
INCBIN "gfx/footprints/types/bug.1bpp",     footprint_top ;Scizor
INCBIN "gfx/footprints/types/bug.1bpp",    footprint_top ;Shuckle
INCBIN "gfx/footprints/types/bug.1bpp",  footprint_top ;Heracross
INCBIN "gfx/footprints/types/normal.1bpp",   footprint_top ;Tungtyed
INCBIN "gfx/footprints/types/normal.1bpp",  footprint_top ;Teddiursa
; 209-216 second type
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Snubbull
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Granbull
INCBIN "gfx/footprints/types/poison.1bpp",   footprint_bottom ;Qwilfish
INCBIN "gfx/footprints/types/steel.1bpp",     footprint_bottom ;Scizor
INCBIN "gfx/footprints/types/rock.1bpp",    footprint_bottom ;Shuckle
INCBIN "gfx/footprints/types/fighting.1bpp",  footprint_bottom ;Heracross
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Tungtyed
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Teddiursa
; 217-224 first type
INCBIN "gfx/footprints/types/normal.1bpp",   footprint_top ;Ursaring
INCBIN "gfx/footprints/types/fire.1bpp",     footprint_top ;Slugma
INCBIN "gfx/footprints/types/fire.1bpp",   footprint_top ;Magcargo
INCBIN "gfx/footprints/types/ice.1bpp",     footprint_top ;Swinub
INCBIN "gfx/footprints/types/ice.1bpp",  footprint_top ;Piloswine
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Corsola
INCBIN "gfx/footprints/types/water.1bpp",   footprint_top ;Remoraid
INCBIN "gfx/footprints/types/water.1bpp",  footprint_top ;Octillery
; 217-224 second type
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Ursaring
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Slugma
INCBIN "gfx/footprints/types/rock.1bpp",   footprint_bottom ;Magcargo
INCBIN "gfx/footprints/types/ground.1bpp",     footprint_bottom ;Swinub
INCBIN "gfx/footprints/types/ground.1bpp",  footprint_bottom ;Piloswine
INCBIN "gfx/footprints/types/rock.1bpp",    footprint_bottom ;Corsola
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Remoraid
INCBIN "gfx/footprints/types/none.1bpp",  footprint_bottom ;Octillery
; 225-232 first type
INCBIN "gfx/footprints/types/ice.1bpp",   footprint_top ;Delibird
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Mantine
INCBIN "gfx/footprints/types/steel.1bpp",   footprint_top ;Skarmory
INCBIN "gfx/footprints/types/fire.1bpp",   footprint_top ;Houndour
INCBIN "gfx/footprints/types/fire.1bpp",   footprint_top ;Houndoom
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Kingdra
INCBIN "gfx/footprints/types/ground.1bpp",     footprint_top ;Phanpy
INCBIN "gfx/footprints/types/ground.1bpp",    footprint_top ;Donphan
; 225-232 second type
INCBIN "gfx/footprints/types/flying.1bpp",   footprint_bottom ;Delibird
INCBIN "gfx/footprints/types/flying.1bpp",    footprint_bottom ;Mantine
INCBIN "gfx/footprints/types/flying.1bpp",   footprint_bottom ;Skarmory
INCBIN "gfx/footprints/types/dark.1bpp",   footprint_bottom ;Houndour
INCBIN "gfx/footprints/types/dark.1bpp",   footprint_bottom ;Houndoom
INCBIN "gfx/footprints/types/dragon.1bpp",    footprint_bottom ;Kingdra
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Phanpy
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Donphan
; 233-240 first type
INCBIN "gfx/footprints/types/normal.1bpp",   footprint_top ;Porygon2
INCBIN "gfx/footprints/types/normal.1bpp",   footprint_top ;Stantler
INCBIN "gfx/footprints/types/normal.1bpp",   footprint_top ;Smeargle
INCBIN "gfx/footprints/types/grass.1bpp",    footprint_top ;Tangrowth
INCBIN "gfx/footprints/types/ghost.1bpp",  footprint_top ;Gremini
INCBIN "gfx/footprints/types/ice.1bpp",   footprint_top ;Smoochum
INCBIN "gfx/footprints/types/electric.1bpp",     footprint_top ;Elekid
INCBIN "gfx/footprints/types/fire.1bpp",      footprint_top ;Magby
; 233-240 second type
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Porygon2
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Stantler
INCBIN "gfx/footprints/types/none.1bpp",   footprint_bottom ;Smeargle
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Tangrowth
INCBIN "gfx/footprints/types/dark.1bpp",  footprint_bottom ;Gremini
INCBIN "gfx/footprints/types/psychic.1bpp",   footprint_bottom ;Smoochum
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Elekid
INCBIN "gfx/footprints/types/none.1bpp",      footprint_bottom ;Magby
; 241-248 first type
INCBIN "gfx/footprints/types/normal.1bpp",    footprint_top ;Miltank
INCBIN "gfx/footprints/types/normal.1bpp",    footprint_top ;Blissey
INCBIN "gfx/footprints/types/electric.1bpp",     footprint_top ;Raikou
INCBIN "gfx/footprints/types/fire.1bpp",      footprint_top ;Entei
INCBIN "gfx/footprints/types/water.1bpp",    footprint_top ;Suicune 
INCBIN "gfx/footprints/types/rock.1bpp",   footprint_top ;Larvitar
INCBIN "gfx/footprints/types/rock.1bpp",    footprint_top ;Pupitar
INCBIN "gfx/footprints/types/rock.1bpp",  footprint_top ;Tyranitar
; 241-248 second type
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Miltank
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Blissey
INCBIN "gfx/footprints/types/none.1bpp",     footprint_bottom ;Raikou
INCBIN "gfx/footprints/types/none.1bpp",      footprint_bottom ;Entei
INCBIN "gfx/footprints/types/none.1bpp",    footprint_bottom ;Suicune 
INCBIN "gfx/footprints/types/ground.1bpp",   footprint_bottom ;Larvitar
INCBIN "gfx/footprints/types/ground.1bpp",    footprint_bottom ;Pupitar
INCBIN "gfx/footprints/types/dark.1bpp",  footprint_bottom ;Tyranitar
; 249-256 first type
INCBIN "gfx/footprints/types/psychic.1bpp",      footprint_top ;Lugia
INCBIN "gfx/footprints/types/fire.1bpp",      footprint_top ;Ho-Oh
INCBIN "gfx/footprints/types/grass.1bpp",     footprint_top ;Celebi
INCBIN "gfx/footprints/types/water.1bpp",     footprint_top ;Octank
INCBIN "gfx/footprints/253.1bpp",        footprint_top
INCBIN "gfx/footprints/254.1bpp",        footprint_top
INCBIN "gfx/footprints/255.1bpp",        footprint_top
INCBIN "gfx/footprints/256.1bpp",        footprint_top
; 249-256 second type
INCBIN "gfx/footprints/types/flying.1bpp",      footprint_bottom ;Lugia
INCBIN "gfx/footprints/types/flying.1bpp",      footprint_bottom ;Ho-Oh
INCBIN "gfx/footprints/types/psychic.1bpp",     footprint_bottom ;Celebi
INCBIN "gfx/footprints/types/steel.1bpp",     footprint_bottom ;Octank
INCBIN "gfx/footprints/253.1bpp",        footprint_bottom
INCBIN "gfx/footprints/254.1bpp",        footprint_bottom
INCBIN "gfx/footprints/255.1bpp",        footprint_bottom
INCBIN "gfx/footprints/256.1bpp",        footprint_bottom
